<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cd4ab14d-2cbb-424d-9661-d1c1b3770e6b</elementGuidId>
    <imagePath></imagePath>
    <name>link_cloudDesktopSolutions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/section[2]/div[2]/div[1]/div[2]/div[1]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'linkElement') and equals(@href,'https://mohit3021.wixsite.com/qcitech-solutions/cloud-desktop') and equals(@text,'Learn More')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#comp-j7gf5qv01 &gt; .uDW_Qe</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>linkElement</value>
        <webElementGuid>7a8f1892-ecf0-499d-843d-3bf23844c194</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://mohit3021.wixsite.com/qcitech-solutions/cloud-desktop</value>
        <webElementGuid>7a8f1892-ecf0-499d-843d-3bf23844c194</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Learn More</value>
        <webElementGuid>7a8f1892-ecf0-499d-843d-3bf23844c194</webElementGuid>
    </webElementProperties>
</WebElementEntity>