<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa12aeb2-ba6f-4d34-a9dd-304ecd4ff685</elementGuidId>
    <imagePath></imagePath>
    <name>link_aboutUs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[1]/header[1]/div[2]/div[2]/div[1]/div[1]/wix-dropdown-menu[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'linkElement') and equals(@href,'https://mohit3021.wixsite.com/qcitech-solutions') and equals(@text,'About Us')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="About Us"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>linkElement</value>
        <webElementGuid>e4aff8ac-adef-4a90-9377-11a2e6a7593f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://mohit3021.wixsite.com/qcitech-solutions</value>
        <webElementGuid>e4aff8ac-adef-4a90-9377-11a2e6a7593f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>About Us</value>
        <webElementGuid>e4aff8ac-adef-4a90-9377-11a2e6a7593f</webElementGuid>
    </webElementProperties>
</WebElementEntity>